database:
  host: localhost
  port: 3306
  db_name: test
  user: root
  password: "123456"
enabled: true
tags:
  - "dev"
  - "web"

INFLUX_DB:
  URL: http://localhost:8181
  TOKEN: apiv3_ntcKjOE7rToG5Z9tcxJ9XQj1_8Bm-ANFgIECpNtyhPeBuSJstAglB_pF1awNFt9oUcCZL4Og9kwd3wnMDG29gQ

granaries:
  - code: '001'
    PLC_IP: 192.168.0.20
    PLC_PORT: 503
    devices_addr:
      windows:
        - 1
        - 10
      # 风门
      dampers:
        - 11
        - 18
      # 风机
      blowers:
        - 19
        - 26
      # 排风扇
      exhaustFans:
        - 27
        - 30  
      # 空调
      airConditioners:
        - 33
        - 34
      temp:
        - 35
        - 174
      humid:
        - 175
        - 314
      window-state:
        - 365
        - 374
      
  - code: '002'
    PLC_IP: 192.168.0.20
    PLC_PORT: 502